name: Build Edge
on:
  push:
    branches:
      - main
jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build and Push Latest
        uses: docker/build-push-action@v1.1.0
        with:
          repository: dkolb/crafty-controller
          username: dkolb
          password: ${{ secrets.DOCKER_TOKEN }}
          tag_with_ref: false
          edge: edge
          add_git_labels: true
