name: Build and Push Release
on:
  push:
    tags:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push release
        uses: docker/build-push-action@v1.1.0
        with:
          repository: dkolb/crafty-controller
          username: dkolb
          password: ${{ secrets.DOCKER_TOKEN }}
          tag_with_ref: true
          add_git_labels: true
