name: Check Build
on: pull_request
jobs:
  check-build:
    name: Check Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Push release
        uses: docker/build-push-action@v1.1.0
        env:
          DOCKER_BUILDKIT: 1
        with:
          repository: dkolb/crafty-controller
          username: dkolb
          password: ${{ secrets.DOCKER_TOKEN }}
          tag_with_ref: true
          tags: latest
          add_git_labels: true
          cache_froms: dkolb/crafty-controller:edge
          buld_args: BUILDKIT_INLINE_CACHE=1
          push: false
